# version: "3"
# services:
#   frontend:
#     image: gitlab.com/steppelink/readium/frontend:latest
#   lcpserver:
#     image: gitlab.com/steppelink/readium/lcpserver:latest
#   lsdserver:
#     image: gitlab.com/steppelink/readium/lsdserver:latest

version: "3.7"
services:
  license-server:
    build: # Info to build the Docker image
      context: ./Dockerfiles # Specify where the Dockerfile is located (e.g. in the root directory of the project)
      dockerfile: LicenseServer # Specify the name of the Dockerfile
    restart: on-failure

    ports:
      - 8989:8989
    environment: # You can use this section to set environment variables. But you can also use the .env file.
      - READIUM_LCPSERVER_CONFIG=/etc/readium-lcp-server/lcp-config.yaml # configuration file
    volumes:
      - /etc/readium-lcp-server:/etc/readium-lcp-server:cached
      - /readium/lcpfiles:/readium/lcpfiles
    networks:
      - readium # Docker containers (services) that need to connect to each other should be on the same network.
  license-status-server:
    build:
      context: ./Dockerfiles
      dockerfile: LicenseStatusServer
    restart: on-failure
    ports:
      - 8990:8990
    environment:
      - READIUM_LSDSERVER_CONFIG=/etc/readium-lcp-server/lsd-config.yaml
    volumes:
      - /etc/readium-lcp-server:/etc/readium-lcp-server:cached
      - /readium/lcpfiles:/readium/lcpfiles
    networks:
      - readium
networks:
  readium:
