
frontend:
  host: "${HOST}"
  port: "${PORT}"
  directory: "${DIRECTORY}"
  public_base_url: "${FRONTEND_BASE_URL}"
  database: "${DB_URI}"
  master_repository: "${MASTER_REPOSITORY}"
  encrypted_repository: "${ENCRYPTED_REPOSITORY}"
  provider_uri: "${PROVIDER_URI}"
  right_print: ${RIGHT_PRINT_NUMBER}
  right_copy: ${RIGHT_COPY_NUMBER}

lsd:
  public_base_url: "${LSD_BASE_URL}"
lcp:
  public_base_url: "${LCP_BASE_URL}"
lcp_update_auth:
  username: "${LCP_UPDATE_AUTH_USER}"
  password: "${LCP_UPDATE_AUTH_PASS}"
lsd_notify_auth: 
  username: "${LSD_NOTIFY_AUTH_USER}"
  password: "${LSD_NOTIFY_AUTH_PASS}"
storage:
  Mode: "s3" # be careful need uppercase
  Endpoint: "${S3_ENDPOINTS}"
  access_id: "${S3_ACCESS_ID}"
  disable_ssl: "${S3_DISABLE_SSL}"
  Secret: "${S3_SECRET}"
  Bucket: "${S3_BUCKET}"
  Region: "${S3_REGION}"
  Token: "${S3_TOKEN}"
