profile: "basic"
lcp:
  host: "0.0.0.0"
  port: 8989
  public_base_url: "http://127.0.0.1:8989/lcpserver"
  database: "sqlite3://file:/usr/local/var/readium/db/lcp.sqlite?cache=shared&mode=rwc"
  auth_file: "/usr/local/etc/readium/htpasswd"
certificate:
  cert: "/usr/local/var/readium/lcp/cert/cert.pem"
  private_key: "/usr/local/var/readium/lcp/cert/privkey.pem"
license:
  links:
    status: "https://www.example.net/lsdserver/licenses/{license_id}/status"
    hint: "https://www.example.net/static/lcp_hint.html"

lsd_notify_auth:
  username: "admin"
  password: "admin"

lsd:
  host: "0.0.0.0"
  port: 8990
  public_base_url: "http://127.0.0.1:8990"
  database: "sqlite3://file:/usr/local/var/readium/db/lsd.sqlite?cache=shared&mode=rwc"
  auth_file: "/usr/local/etc/readium/htpasswd"
  license_link_url: "https://www.example.net/lcp/licenses/{license_id}"
license_status:
  register: true
  renew: true
  return: true
  renting_days: 60
  renew_days: 7

lcp_update_auth:
  username: "admin"
  password: "admin"
